site_name: Autonomous Warehouse Patrolling Robot
theme:
  name: material

nav:
  - ğŸ  Home: index.md
  - ğŸ“Š Project Outputs: outputs.md
  - ğŸ§­ Initial Project Plan: initialplan.md
  - ğŸ§° Code Walkthrough: codewalkthrough.md
  - ğŸš€ Launch Instructions: launch.md
  - ğŸ¥ Videos: videos.md
  - ğŸ§  ROS2 Architecture: ros2_architecture.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
